config/routes.rb
Rails.application.routes.draw do

  # /
  root 'events#index'
  resources :events, :only => [:index]

  namespace :api do
    get 'search/events', to: 'search#events'
    post 'filters', to: 'filters#create'
  end

  # для наглядности
  resources  :filters, only: [:index, :create, :destroy]
  resources  :notifications, only: [:index, :show]
end

app/models/event.rb
class Event < ActiveRecord::Base
  include Notifications

  reverse_geocoded_by :latitude, :longitude

  has_many :notifications, dependent: :destroy
  belongs_to :user
  has_many :events_games
  has_many :games, through: :events_games

  after_create :set_notifications
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @filter = Filter.new
  end

end

app/views/events/_event.slim
tr
  th.bold Name
  th.bold Start at
  th.bold End at

tr.event-template.none
  td.name
    |xx
  td.start_at
    |xx
  td.end_at
    |yy

app/views/events/_form.html.slim
= simple_form_for(@event, remote: true, format: :json) do |f|
  = f.error_notification

  = f.input :name
  = f.input :start_at, as: :string, input_html: {class: 'datetimepicker'}
  = f.input :end_at, as: :string, input_html: {class: 'datetimepicker'}
  = f.input :latitude
  = f.input :longitude

  .form-actions
    = f.button :submit, 'Save Event', class: 'pull-right', id: 'save_event'

app/views/events/index.slim
h1 Events

= render 'filters/form'
.form-actions.find_events_wrapper
  input id="find_events" data-action="#{api_search_events_path}" onclick="App.filters.find($(this));" type="submit" value="Find Events" class="btn btn-primary pull-left"

.clearfix

table#events_table.table.mt-40
  = render 'event'