config/routes.rb
Rails.application.routes.draw do

  # /
  root 'events#index'
  resources :events, :only => [:index]

  namespace :api do
    get 'search/events', to: 'search#events'
    post 'filters', to: 'filters#create'
  end

  # для наглядности
  resources  :filters, only: [:index, :create, :destroy]
  resources  :notifications, only: [:index, :show]
end

app/models/event.rb
class Event < ActiveRecord::Base
  include Notifications

  reverse_geocoded_by :latitude, :longitude

  has_many :notifications, dependent: :destroy
  belongs_to :user
  has_many :events_games
  has_many :games, through: :events_games

  after_create :set_notifications
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  belongs_to :user
end

app/controllers/api/filters_controller.rb
class Api::FiltersController < Api::BaseController

  def create
      prepared_params = FilterParams.new(filter_params, true)
      if prepared_params.success?
        data = prepared_params.data

        data.delete_if { |key, value| !key.to_s.in? ['start_from', 'start_to', 'start_date', 'max_distance', 'game_ids'] }

        @filter = current_user.filters.new(data)

        if @filter.save
          render json: {success: true, filter: @filter.to_json}
        else
          render json: {errors: @filter.errors.to_json}, status: :unprocessable_entity
        end

      else
        render json: {errors: prepared_params.errors.to_json}, status: :unprocessable_entity
      end
  end

  private

    def filter_params
      params.fetch(:filter, {}).permit(:start_from, :start_to, :start_date, :max_distance, game_ids: [])
    end

end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  before_action :set_filter, only: [:show, :edit, :update, :destroy]

  # для наглядности - проверить что фильтры создаются, удалтиь ненужные
  def index
    @filters = current_user.filters
  end

  def destroy
    notifications = Notification.where(user: current_user, filter: @filter)
    notifications.destroy_all if notifications.any?
    @filter.destroy

    respond_to do |format|
      format.html { redirect_to filters_url, notice: 'Filter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_filter
      @filter = Filter.find(params[:id])
    end

end

app/views/filters/_form.html.slim
= simple_form_for(@filter, url: api_filters_path(format: :json), remote: true) do |f|
  = f.error_notification

  = f.input :start_from, input_html: {class: 'hourpicker'}
  = f.input :start_to, input_html: {class: 'hourpicker'}
  = f.input :start_date, as: :select, collection: Date::DAYNAMES.map { |day| day }
  = f.input :max_distance
  = f.input :game_ids, collection: Game.all, input_html: { multiple: true }
  /.clearfix
  .form-actions
    = f.button :submit, 'Save Filter', class: 'pull-right', id: 'save_filter'
    /.clearfix

app/views/filters/index.html.slim
.page-header
  h1
    | Listing filters

.table-responsive
  table.table.table-striped.table-hover
    thead
      tr
        th
          |start_from
        th
          |start_to
        th
          |start_date
        th
          |max_distance
        th
          | games
        th
    tbody
      - @filters.each do | filter |
        tr
          td = filter.start_from
          td = filter.start_to
          td = date_format(filter.start_date) if filter.start_date.present?
          td = filter.max_distance
          td = Game.where(id: filter.game_ids).pluck(:name).join(',')
          td = link_to 'Destroy', filter, method: :delete, data: { confirm: 'Are you sure?' }