config/routes.rb
Rails.application.routes.draw do

  # /
  root 'events#index'
  resources :events, :only => [:index]

  namespace :api do
    get 'search/events', to: 'search#events'
    post 'filters', to: 'filters#create'
  end

  # для наглядности
  resources  :filters, only: [:index, :create, :destroy]
  resources  :notifications, only: [:index, :show]
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "App"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to 'App', root_path, class: 'navbar-brand'
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li = link_to "My Filters", filters_path
            li = link_to "Notifications (#{current_user.active_notifications.count})", notifications_path

    .container
      .row#main-content
        .col-lg-12
          #bootstrap_flashes
            = bootstrap_flash
          - if content_for?(:header)
            .page-header
              h1 = yield :header
          = yield


      footer
        p &copy; App 2016